name: Backup posts in markdown

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download markdown files
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: sh update.sh
      - name: Commit and push changes
        run: |
          git config --local user.name 'GitHub Action'
          git config --local user.email action@github.com
          git add -f 20*
          if [ $(git status -s | wc -l) -ne 0 ]; then
            git commit -m "Update posts"
            git push https://${{ github.actor }}:${{ secrets.REPO_TOKEN }}@github.com/${{ github.repository }}.git HEAD:master
          else
            echo "Nothing to update"
          fi
